project:
  type: website

website:
  title: "Scott H. Hawley"
  site-url: https://drscotthawley.github.io/blog
  favicon: images/logo.png
  twitter-card: true
  drafts: unlinked
  navbar:
    logo: images/logo.png
    logo-alt: "SH Logo"
    logo-href: https://www.scotthawley.com
    title-href: https://www.scotthawley.com
    right:
      - about.qmd
      - icon: github
        href: https://github.com/drscotthawley
      - text: '{{< fa brands bluesky >}}'
        href: https://bsky.app/profile/drscotthawley.bsky.social
      - icon: twitter
        href: https://twitter.com/drscotthawley
      - icon: linkedin
        href: https://www.linkedin.com/in/drscotthawley/
format:
  html:
    theme: darkly
    css: styles.css
    link-external-newwindow: true
    highlight-style: monokai
    include-in-header:
      - custom_css.css
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@500;600;700&display=swap" rel="stylesheet">
execute:
  freeze: auto


